### ISSUE TITLE
Getting to the top/bottom of discussions with many posts

### ISSUE THREAD

**Issue by iamdarkle** [datlechin/flarum-scroll-buttons#1]
I don't know how feasible this is, as I guess you would have to add additional logic, but I think it would be quite useful. 

Currently within the discussions the up and down buttons act trying to get to the top/bottom part of the screen, the problem with this is that if a discussion has many posts, when for example you hit the button to go up there comes a point that reaches the top and stops there because they must load the following posts to continue, so you can not get to the top. I don't know if I make myself clear, I hope so. 

I think the solution to this would be to copy the behaviour of these buttons from here:

![Screenshot 2022-02-09 205322](https://user-images.githubusercontent.com/15818451/153279548-c5feecdf-7492-4de4-a52d-0ad81642c48e.png)

This behaviour should only apply specifically within discussions, I think that would be the best way to avoid this problem.

**Comment by datlechin** [comment]
nice idea, will have a release soon

**Comment by datlechin** [comment]
new version is released
