### ISSUE TITLE
Icon not displayed

### ISSUE THREAD

**Issue by swra1nb0w** [datlechin/flarum-scroll-buttons#11]
![](https://zwhy-1310134253.cos.ap-beijing.myqcloud.com/screenshot.png)

**Comment by phuocvj** [comment]
Same issues. Plz check and update ext!

**Comment by datlechin** [comment]
Looks like you're using [Fluent Theme](https://discuss.flarum.org/d/33246-fluent-theme), I've tested and those icons still there.

Can you share your `php flarum info`?

<img width="1143" alt="Screenshot 2024-06-13 at 01 36 06" src="https://github.com/datlechin/flarum-scroll-buttons/assets/56961917/73d4e20f-da4e-4001-b875-b4ca340109f4">
